"""empty message

Revision ID: 051886d4dd55
Revises: 6e9e621f272b
Create Date: 2021-10-20 00:02:49.892746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051886d4dd55'
down_revision = '6e9e621f272b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training', 'lst_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('lst_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

import sqlalchemy_utils
