"""empty message

Revision ID: 17f256558d13
Revises: d7790c96081c
Create Date: 2021-10-03 20:08:14.219563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f256558d13'
down_revision = 'd7790c96081c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('trainer', sa.String(length=128), nullable=True))
    op.add_column('training', sa.Column('specialization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'training', 'specialization', ['specialization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.drop_column('training', 'specialization_id')
    op.drop_column('training', 'trainer')
    # ### end Alembic commands ###

import sqlalchemy_utils
