"""empty message

Revision ID: 2107a3bc9747
Revises: 26e920760c09
Create Date: 2021-10-01 17:13:32.015013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2107a3bc9747'
down_revision = '26e920760c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('specialization', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('specialization')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialization')
    # ### end Alembic commands ###
