"""empty message

Revision ID: 34fd6d343cc7
Revises: 5dd8d310c08a
Create Date: 2021-10-03 18:26:57.350796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fd6d343cc7'
down_revision = '5dd8d310c08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_specialization',
    sa.Column('traine_id', sa.Integer(), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['specialization_id'], ['specialization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traine_id'], ['trainer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('traine_id', 'specialization_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainer_specialization')
    # ### end Alembic commands ###

import sqlalchemy_utils
