"""empty message

Revision ID: 3dba2d914400
Revises: 34fd6d343cc7
Create Date: 2021-10-03 18:27:49.252013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dba2d914400'
down_revision = '34fd6d343cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_specialization', sa.Column('trainer_id', sa.Integer(), nullable=False))
    op.drop_constraint('trainer_specialization_traine_id_fkey', 'trainer_specialization', type_='foreignkey')
    op.create_foreign_key(None, 'trainer_specialization', 'trainer', ['trainer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('trainer_specialization', 'traine_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_specialization', sa.Column('traine_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trainer_specialization', type_='foreignkey')
    op.create_foreign_key('trainer_specialization_traine_id_fkey', 'trainer_specialization', 'trainer', ['traine_id'], ['id'], ondelete='CASCADE')
    op.drop_column('trainer_specialization', 'trainer_id')
    # ### end Alembic commands ###

import sqlalchemy_utils
