"""empty message

Revision ID: 5dd8d310c08a
Revises: 7c4f2f75032d
Create Date: 2021-10-03 17:59:31.316067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd8d310c08a'
down_revision = '7c4f2f75032d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('learner', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('trainer', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'learner', ['learner'], ['id'])
    op.create_foreign_key(None, 'user', 'trainer', ['trainer'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'trainer')
    op.drop_column('user', 'learner')
    # ### end Alembic commands ###

import sqlalchemy_utils
