"""empty message

Revision ID: 63d8bbb58959
Revises: 6961a3bf1a3c
Create Date: 2021-10-05 22:32:17.962355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d8bbb58959'
down_revision = '6961a3bf1a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainer', 'gender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainer', 'gender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###

import sqlalchemy_utils
