"""empty message

Revision ID: 6961a3bf1a3c
Revises: 633915c1d1ad
Create Date: 2021-10-05 20:10:20.167648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6961a3bf1a3c'
down_revision = '633915c1d1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('_password', sa.String(length=200), nullable=True),
    sa.Column('photo', sa.String(length=20), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('learner', sa.Integer(), nullable=True),
    sa.Column('trainer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['learner'], ['learner.id'], ),
    sa.ForeignKeyConstraint(['trainer'], ['trainer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_foreign_key(None, 'training_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_user', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###

import sqlalchemy_utils
