"""empty message

Revision ID: 6de4ae78d3a9
Revises: 50edfc0c898b
Create Date: 2021-10-01 16:20:08.792092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de4ae78d3a9'
down_revision = '50edfc0c898b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gender_traine')
    op.drop_table('group')
    op.drop_table('gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gender_pkey'),
    sa.UniqueConstraint('gender', name='gender_gender_key')
    )
    op.create_table('group',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='group_pkey'),
    sa.UniqueConstraint('group', name='group_group_key')
    )
    op.create_table('gender_traine',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gender_traine', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gender_traine_pkey'),
    sa.UniqueConstraint('gender_traine', name='gender_traine_gender_traine_key')
    )
    # ### end Alembic commands ###
