"""empty message

Revision ID: 6e9e621f272b
Revises: aad34ece2d1e
Create Date: 2021-10-19 23:34:13.242749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9e621f272b'
down_revision = 'aad34ece2d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'training', 'users', ['creator_id'], ['id'])
    op.drop_column('training', 'trainer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('trainer', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.drop_column('training', 'creator_id')
    # ### end Alembic commands ###

import sqlalchemy_utils
