"""empty message

Revision ID: 75c745a28f52
Revises: 92599035821d
Create Date: 2021-10-01 15:57:11.361860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c745a28f52'
down_revision = '92599035821d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gender_pkey'),
    sa.UniqueConstraint('gender', name='gender_gender_key')
    )
    # ### end Alembic commands ###
