"""empty message

Revision ID: 7c50142de0f3
Revises: 63d8bbb58959
Create Date: 2021-10-17 20:56:25.830362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c50142de0f3'
down_revision = '63d8bbb58959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trainer_specialization_specialization_id_fkey', 'trainer_specialization', type_='foreignkey')
    op.drop_constraint('trainer_specialization_trainer_id_fkey', 'trainer_specialization', type_='foreignkey')
    op.create_foreign_key(None, 'trainer_specialization', 'trainer', ['trainer_id'], ['id'])
    op.create_foreign_key(None, 'trainer_specialization', 'specialization', ['specialization_id'], ['id'])
    op.drop_constraint('training_user_user_id_fkey', 'training_user', type_='foreignkey')
    op.create_foreign_key(None, 'training_user', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'photo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'photo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'training_user', type_='foreignkey')
    op.create_foreign_key('training_user_user_id_fkey', 'training_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'trainer_specialization', type_='foreignkey')
    op.drop_constraint(None, 'trainer_specialization', type_='foreignkey')
    op.create_foreign_key('trainer_specialization_trainer_id_fkey', 'trainer_specialization', 'trainer', ['trainer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('trainer_specialization_specialization_id_fkey', 'trainer_specialization', 'specialization', ['specialization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

import sqlalchemy_utils
