"""empty message

Revision ID: 8425ec56f354
Revises: 75c745a28f52
Create Date: 2021-10-01 15:59:04.530799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8425ec56f354'
down_revision = '75c745a28f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gender_traine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender_traine',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gender_traine', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gender_traine_pkey'),
    sa.UniqueConstraint('gender_traine', name='gender_traine_gender_traine_key')
    )
    # ### end Alembic commands ###
