"""empty message

Revision ID: 9bce18040fed
Revises: b67f75bfe1c9
Create Date: 2021-10-22 15:02:23.745326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bce18040fed'
down_revision = 'b67f75bfe1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialization', sa.Column('color', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'specialization', ['color'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialization', type_='unique')
    op.drop_column('specialization', 'color')
    # ### end Alembic commands ###

import sqlalchemy_utils
