"""empty message

Revision ID: a63c22791672
Revises: f7a0cb724d01
Create Date: 2021-10-03 17:04:40.859630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63c22791672'
down_revision = 'f7a0cb724d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group_id', sa.Integer(), nullable=True))
    op.alter_column('user', 'photo',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_foreign_key(None, 'user', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('user', 'photo',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('user', 'group_id')
    # ### end Alembic commands ###
