"""empty message

Revision ID: b67f75bfe1c9
Revises: 527259a66dc0
Create Date: 2021-10-21 16:37:07.311396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67f75bfe1c9'
down_revision = '527259a66dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('number', sa.Integer(), nullable=True))
    op.drop_constraint('training_description_key', 'training', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('training_description_key', 'training', ['description'])
    op.drop_column('training', 'number')
    # ### end Alembic commands ###

import sqlalchemy_utils
