"""empty message

Revision ID: edbbc2e719c8
Revises: 86763e495842
Create Date: 2021-10-19 23:26:52.165168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbbc2e719c8'
down_revision = '86763e495842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gender_traine')
    op.drop_constraint('training_gender_id_fkey', 'training', type_='foreignkey')
    op.create_foreign_key(None, 'training', 'gender', ['gender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.create_foreign_key('training_gender_id_fkey', 'training', 'gender_traine', ['gender_id'], ['id'])
    op.create_table('gender_traine',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gender_traine', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gender_traine_pkey'),
    sa.UniqueConstraint('gender_traine', name='gender_traine_gender_traine_key')
    )
    # ### end Alembic commands ###

import sqlalchemy_utils
